### ISSUE TITLE
Square color not updating when setting input value

### ISSUE THREAD

**Issue by maximeurbn** [LCweb-ita/LC-color-picker#2]
When I set via JavaScript the value of an input with the color picker, the square doesn't change color until I click on it. Is there a way to trigger an update and force this color change ?

**Comment by LCweb-ita** [comment]
Hello, clearly the tool reacts to user inputs. 
Therefore you have to trigger a "change" or "input" event on the field to let the field to re-sync

**Comment by maximeurbn** [comment]
Okay thank you for your quick answer. I managed to fix my issue
